spring:
  application:
    name: exchange-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

exchange-client:
  url: https://api.exchangerate.host

eureka:
  client:
    enabled: false
